# Generated by Django 5.0.6 on 2024-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_employee_department_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_val', models.CharField(max_length=200)),
                ('authenticated', models.BooleanField(default=True)),
            ],
        ),
    ]
