# Generated by Django 5.0.6 on 2024-06-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
