# Generated by Django 5.0.6 on 2024-06-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_requestattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestattempt',
            old_name='success',
            new_name='succeed',
        ),
    ]
