# Generated by Django 5.0.6 on 2024-06-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_requestattempt_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestattempt',
            old_name='succeed',
            new_name='successful',
        ),
    ]
