# Generated by Django 5.0.6 on 2024-06-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_rename_succeed_requestattempt_successful'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='card',
            name='authenticated',
        ),
    ]
